In [1]:
import numpy as np

## DataTypes and Atributes of numpy

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3 = np.array([[[1,2,4],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  4],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [21]:
df3 = pd.DataFrame(a1)
df3

0
0  1
1  2
2  3

# Creating Arrays

In [33]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
zeros.dtype

dtype('float64')

In [37]:
zeros.size

12

In [39]:
range_array = np.arange(0,29,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [40]:
range_array.size

15

In [42]:
range_array.shape

(15,)

In [46]:
random_array = np.random.randint(2,10,size=(3,5))
random_array

array([[4, 3, 3, 8, 3],
       [8, 4, 5, 9, 8],
       [2, 2, 5, 9, 4]])

In [47]:
random_array2 = np.random.rand(3,2)
random_array2

array([[0.24222038, 0.20106998],
       [0.46687755, 0.67659202],
       [0.37524312, 0.82714997]])

### Pseudo-Random Numbers

In [70]:
 x = np.random.seed(seed=5)
random_array_3 = np.random.random((2,3))
random_array_3

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386]])

In [81]:
np.random.seed(seed=7)
random_array_4 = np.random.random((4,3))
random_array_4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904]])