In [2]:
import numpy as np

# Reshaping

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array([[9,8,4],[5,6,7]])
b

array([[9, 8, 4],
       [5, 6, 7]])

In [5]:
c = np.array([
    [[1,3,4],[5,6,7]],
    [[7,6,4],[7,4,9]]
])
c

array([[[1, 3, 4],
        [5, 6, 7]],

       [[7, 6, 4],
        [7, 4, 9]]])

In [6]:
a.shape,b.shape, c.shape

((6,), (2, 3), (2, 2, 3))

In [7]:
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [8]:
c[1,0,0] = 88
c[1,1,1] = 55
c

array([[[ 1,  3,  4],
        [ 5,  6,  7]],

       [[88,  6,  4],
        [ 7, 55,  9]]])

In [9]:
c.shape

(2, 2, 3)

In [10]:
new_c = c.reshape(3,2,2)
new_c

array([[[ 1,  3],
        [ 4,  5]],

       [[ 6,  7],
        [88,  6]],

       [[ 4,  7],
        [55,  9]]])

In [11]:
new_c2 = c.reshape(3,4)
new_c2

array([[ 1,  3,  4,  5],
       [ 6,  7, 88,  6],
       [ 4,  7, 55,  9]])

In [12]:
new_c2.shape, new_c2.ndim, new_c2.dtype

((3, 4), 2, dtype('int64'))

In [13]:
new_a = a.reshape((2,3))
new_a
a

array([1, 2, 3, 4, 5, 6])

In [14]:
new_a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
new_a + b

array([[10, 10,  7],
       [ 9, 11, 13]])

In [16]:
b.ndim, c.ndim

(2, 3)

# b.shape, c.shape

In [17]:
new_a2 = c.reshape(2,2,3)
new_a2

array([[[ 1,  3,  4],
        [ 5,  6,  7]],

       [[88,  6,  4],
        [ 7, 55,  9]]])

# Array Iteration

In [18]:
for item in np.nditer(c):
    print(item)

1
3
4
5
6
7
88
6
4
7
55
9


In [19]:
for x in c:
    for y in x:
        for z in y:
            print(z)

1
3
4
5
6
7
88
6
4
7
55
9


In [20]:
concarenate_one = np.concatenate((new_a,b))
concarenate_one

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 4],
       [5, 6, 7]])

In [21]:
concarenate_one.ndim

2

In [22]:
c.sort()
c

array([[[ 1,  3,  4],
        [ 5,  6,  7]],

       [[ 4,  6, 88],
        [ 7,  9, 55]]])

# Random Array

In [23]:
rand_arr = np.random.randint(100,size=(10))
rand_arr

array([38, 20, 42, 53, 84, 34, 92, 68, 13, 55])

In [24]:
np.random.rand(2,2,4)

array([[[0.85198453, 0.85499734, 0.04350979, 0.15302481],
        [0.42410172, 0.91163924, 0.18778534, 0.97171632]],

       [[0.5450022 , 0.9014377 , 0.39270912, 0.14204735],
        [0.0011499 , 0.96227153, 0.49149699, 0.06162739]]])

In [25]:
np.random.choice(rand_arr,size=(2,5))

array([[92, 68, 92, 38, 34],
       [55, 34, 38, 38, 13]])

In [26]:
np.random.choice([2,3,5,6,7,8,9],size=(2,6))

array([[6, 9, 6, 9, 3, 8],
       [9, 6, 8, 8, 5, 6]])

In [27]:
shuffle_arr = np.array([2,3,5,6,7,8,9])
np.random.shuffle(shuffle_arr)
shuffle_arr

array([6, 2, 5, 8, 9, 7, 3])

In [28]:
np.random.permutation(shuffle_arr)

array([3, 9, 2, 7, 6, 8, 5])

In [35]:
boolian_arr = np.arange(20)
boolian_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
big_bool = boolian_arr > 10
big_bool

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [39]:
boolian_arr[big_bool]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
np.arange(2,50,2).reshape(3,2,4)

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[18, 20, 22, 24],
        [26, 28, 30, 32]],

       [[34, 36, 38, 40],
        [42, 44, 46, 48]]])