# Accessing/ Changing Specific elements, rows, columns, etc

In [3]:
import numpy as np
a = np.array([[2,3,5,6,7,8],[6,5,4,3,2,9]])
a

array([[2, 3, 5, 6, 7, 8],
       [6, 5, 4, 3, 2, 9]])

In [5]:
a[1,5]

9

In [9]:
a[:,2]

array([5, 4])

In [10]:
a[0]

array([2, 3, 5, 6, 7, 8])

In [12]:
sum(a[:])

array([ 8,  8,  9,  9,  9, 17])

In [13]:
a[1,1:4]

array([5, 4, 3])

In [20]:
max(a[1,:])

9

In [21]:
a[:,::-1]

array([[8, 7, 6, 5, 3, 2],
       [9, 2, 3, 4, 5, 6]])

### starttime index - endtime index - stepstime index

In [43]:
a[:,::2] #every other one

array([[2, 5, 7],
       [6, 4, 2]])

In [44]:
a[0,0]  

2

In [45]:
a[0,0]=55

In [46]:
a[0,0]

55

In [47]:
a.dtype

dtype('int64')

In [48]:
a.size

12

In [50]:
a.itemsize

8

In [56]:
a[0,0:4:-2]

array([], dtype=int64)

# 3D Numpy Array

In [68]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [69]:
d.dtype

dtype('int64')

In [70]:
d.shape

(2, 2, 2)

In [71]:
d.ndim

3

In [76]:
d[1,0] = 55,66

In [77]:
d

array([[[ 1,  2],
        [ 3,  4]],

       [[55, 66],
        [ 7,  8]]])

In [78]:
sum(d)

array([[56, 68],
       [10, 12]])

In [79]:
d[0,1]

array([3, 4])

In [81]:
sum(d[1,0])

121

In [83]:
d[::-1]

array([[[55, 66],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]]])